name: CI-CD

on: 
  push: 
    branches: ["main"]

jobs: 
  CI: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.2.2

      - name: Autenticação Docker Hub
        uses: docker/login-action@v3.3.0
        with: 
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}} 
      - name: Construção img Docker
        uses: docker/build-push-action@v6.12.0  
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            inter171991/app:v1.1
            inter171991/app:v1.1
