name: CI-CD

on: 
  push: 
    branches: ["main"]

jobs: 
  CI: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4.2.2
      - name: Construção img Docker
        uses: docker/build-push-action@v6.12.0  
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            davidev17/docker-app:v1.1
            davidev17/docker-app:latest
