name: CI-CD

on: 
  push: 
    branches: ["main"]

jobs: 
  CI: 
    runs-on: ubuntu-latest

    steps: 
      # Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      # Autenticação no Docker Hub
      - name: Autenticação Docker Hub
        uses: docker/login-action@v3.3.0
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      # Construção e Push da Imagem Docker
      - name: Construção e Push da Imagem Docker
        uses: docker/build-push-action@v6.12.0  
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            inter171991/app:${{ github.run_number }}
            inter171991/app:latest

      # Salvar a última tag gerada como variável de ambiente
      - name: Salvar última tag gerada
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

  CD: 
    runs-on: ubuntu-latest
    needs: CI

    steps: 
      # Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4.2.2

      # Instalação do Terraform CLI
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Configuração do Terraform para provisionar a aplicação
      - name: Configurar Infraestrutura com Terraform
        run: |
          terraform init
          terraform apply -auto-approve -var="image_tag=${{ env.IMAGE_TAG }}"
